name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=7.18
  - fastqc=0.11.9
  - multiqc=1.13
  - trimmomatic=0.39
  - bowtie2=2.4.4
  - kraken2=2.1.2
  - metaphlan=3.0.7
  - humann=3.0.0
  - r-base=4.1
  - r-rmarkdown
  - r-knitr
  - r-ggplot2
  - r-dplyr
  - r-plotly
  - r-yaml
  - bioconductor-phyloseq